# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app.core', '0002_auto_20171001_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ofertadetrabajo',
            name='tipo_de_trabajo',
        ),
        migrations.AddField(
            model_name='ofertadetrabajo',
            name='carga_horaria',
            field=models.CharField(default=None, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ofertadetrabajo',
            name='cargo',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ofertadetrabajo',
            name='descripcion_del_trabajo',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ofertadetrabajo',
            name='profesion',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
